### PR TITLE
Login

### PR DESCRIPTION
**Pull request by mbucknell**
The login code, including the Login Manager and login view are in the "auth" blueprint. I generalized the login view to check for safe urls and to redirect to any application url. Used the WSGI_STR configuration parameter to strip the wsgi string from the url.

Note that base.html no longer contains the require.js configuration setup. That is now in manager/templates/manager/manager.html

### CODE REVIEW

**Comment by mbucknell** [comment]
The other noteworthy change is that there is an app wide templates directory and static directory. The templates contains a base.html that is being used for the auth and manager blueprints. The static/less directory contains the usgs_header_footer.less

**Comment by ayan-usgs** [comment]
Thanks for putting together Pubs' auth app!

**Comment by mbucknell** [comment]
I have started writing unit tests using Flask-Tests. The README has been updated with details on running both the lettuce, python unit tests, and jasmine tests.

**Comment by mbucknell** [comment]
Still need to add the service call proxies.

**Pull request merged**
